/*
Copyright (c) 2017, Jairo Rojas-Delgado <jrdelgado@uci.cu>
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
* Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.
* Neither the name of the <organization> nor the
names of its contributors may be used to endorse or promote products
derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef DNN_OPT_CUDA_GENERATORS_UNIFORM
#define DNN_OPT_CUDA_GENERATORS_UNIFORM

#include <curand.h>
#include <cuda/base/generator.h>
#include <core/generators/uniform.h>

namespace dnn_opt
{
namespace cuda
{
namespace generators
{

/**
 * The uniform class represents a uniform distributed random number generator
 * that can used by a solution to generate its initial position in the search
 * space.
 *
 * @author Jairo Rojas-Delgado <jrdelgado@uci.cu>
 * @date September, 2016
 * @version 1.0
 */
class uniform : public generator,
                public core::generators::uniform
{
public:

  /**
   * Create a new instance of the uniform class.
   *
   * @param min the min number that can be generated by this generator.
   *
   * @param dev the max number that can be generated by this generator.
   *
   * @return a pointer to an instance of uniform class.
   */
  static uniform* make(float min, float max);

  void generate(int count, float* params) override;

  virtual float generate() override;

  virtual ~uniform();

protected:

  /**
   * The basic constructor for the uniform class.
   *
   * @param min the min number that can be generated by this generator.
   *
   * @param dev the max number that can be generated by this generator.
   */
  uniform(float min, float max);

  curandGenerator_t _gen;

};
}
}
}

#endif
